version: 2
jobs:
  build:
    docker:
    - image: circleci/node
    branches:
      only:
        - master
    steps:
    - checkout
    - run: npm install -g firebase-tools
    - run: firebase deploy --token "$FIREBASE_TOKEN"
